"""Generate the app's curve paths and crop bounds from the annotated source SVG.

Run with Python's standard library: python docs/design/bodymap/generate.py
"""
from pathlib import Path
import xml.etree.ElementTree as ET

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
NS = '{http://www.w3.org/2000/svg}'
svg = ET.parse(HERE/'bodymap.svg').getroot()
header = '''package com.lsing.timego.ui.common

import com.lsing.timego.data.MuscleGroup

// Generated by docs/design/bodymap/generate.py from bodymap.svg. Edit that source to change art.
/** Standard SVG path with its anatomical assignment and precomputed (left, top, right, bottom)
 * crop bounds. Neutral structural shapes never receive workout intensity. The two-tone artwork
 * uses one lightness for every muscle; heat colors and animation are supplied by the renderer. */
data class MusclePathSpec(
    val pathData: String,
    val muscleGroup: MuscleGroup?,
    val isOutline: Boolean,
    val lightness: Float,
    val bounds: FloatArray,
)

'''

def floats(values):
    return ', '.join(f'{float(v):.3f}f' for v in values)

output = [header]
for side in ['front','back']:
    group = svg.find(f"{NS}g[@id='{side}']")
    box = group.attrib['data-viewbox'].split()
    output.append(f'val {side.upper()}_BODY_VIEWBOX = floatArrayOf({floats(box)})\n\n')
    output.append(f'val {side.upper()}_BODY_PATHS: List<MusclePathSpec> = listOf(\n')
    for path in group.findall(NS+'path'):
        a=path.attrib
        muscle='null' if a['data-muscle']=='NEUTRAL' else 'MuscleGroup.'+a['data-muscle']
        bounds=a['data-bounds'].split()
        assert len(bounds)==4
        assert float(box[0])<=float(bounds[0])<float(bounds[2])<=float(box[2]),a['id']
        assert float(box[1])<=float(bounds[1])<float(bounds[3])<=float(box[3]),a['id']
        output.append(f'    // {a["id"]}\n')
        output.append(f'    MusclePathSpec("{a["d"]}", {muscle}, {a["data-outline"]}, 0.6000f, floatArrayOf({floats(bounds)})),\n')
    output.append(')\n\n')
destination=ROOT/'app/src/main/java/com/lsing/timego/ui/common/MuscleBodyArt.kt'
destination.write_text(''.join(output).rstrip()+'\n',encoding='utf-8')
print(f'Generated {destination.name}')
